apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: team-a
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: team-b
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace